### ISSUE TITLE
Create activities and fragments

### ISSUE THREAD

**Issue by Lkerry** [AyitiTouris/Ayiti_Touris#2]
Create the initial activities and fragments needed for developing early app functionality.

**Comment by LeModele** [comment]
ki activity nap komanse avel la

**Comment by Abrahamas** [comment]
MainActivity an kap genyen ladann welcome page lan kap gen bouton onclick
lan leuw fin clike sou bouton an li gen poul voyew nan home page lan se la
lap gen ladann listview kap genyen lien pou chak hotel yo...

**Comment by Lkerry** [comment]
Good work guys
